/**
 * RetiroSinCuenta.java
 * 13 feb. 2023 22:49:55
 *
 */
package presentacion;

import dominio.Cuenta;
import dominio.Retiros;
import encriptador.Encriptador;
import excepciones.PersistenciaException;
import interfaces.ICuentaDAO;
import java.awt.Frame;
import java.math.BigDecimal;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * Descripción de la clase:
 *
 * @author Daniel Armando Peña Garcia ID:229185
 */
public class GenerarRetiroSinCuentaDlg extends javax.swing.JFrame {

    Frame operacionCliente;
    Cuenta cuenta;
    private final ICuentaDAO cuentaDAO;
    Retiros retiro = null;

    /**
     * Creates new form RetiroSinCuenta
     */
    public GenerarRetiroSinCuentaDlg(Frame operacionCliente, Cuenta cuenta, ICuentaDAO cuentaDAO) {
        this.operacionCliente = operacionCliente;
        this.cuentaDAO = cuentaDAO;
        this.cuenta = cuenta;
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelMonto = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        label$ = new javax.swing.JLabel();
        btnGenerarRetiro = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        labelContrasena = new javax.swing.JLabel();
        passContrasena = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        labelMonto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelMonto.setText("Monto");

        txtMonto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtMonto.setText("00.00");

        label$.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label$.setText("$");

        btnGenerarRetiro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGenerarRetiro.setText("Generar Retiro");
        btnGenerarRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarRetiroActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        labelContrasena.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelContrasena.setText("Contraseña: ");

        passContrasena.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(labelContrasena)
                        .addGap(18, 18, 18)
                        .addComponent(passContrasena))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addGap(44, 44, 44)
                        .addComponent(btnGenerarRetiro))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelMonto)
                        .addGap(18, 18, 18)
                        .addComponent(label$)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label$)
                    .addComponent(labelMonto))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelContrasena)
                    .addComponent(passContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGenerarRetiro))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarRetiroActionPerformed
        double monto = Double.parseDouble(txtMonto.getText());
        String contrasena = encriptar();
        try {
            retiro = cuentaDAO.generarRetiro(cuenta, monto, contrasena);
            JOptionPane.showMessageDialog(this, "El folio que se genero es: "+retiro.getFolio(), "Folio generado", JOptionPane.INFORMATION_MESSAGE);
            operacionCliente.setVisible(true);
            dispose();
        } catch (PersistenciaException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGenerarRetiroActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        operacionCliente.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private String encriptar() {
        char[] arrayPass = passContrasena.getPassword();
        Encriptador encriptador = new Encriptador();
        String passCadena = new String(arrayPass);
        return encriptador.encriptar(passCadena);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGenerarRetiro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label$;
    private javax.swing.JLabel labelContrasena;
    private javax.swing.JLabel labelMonto;
    private javax.swing.JPasswordField passContrasena;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables

}
