/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import dominio.Cliente;
import dominio.Cuenta;
import excepciones.PersistenciaException;
import interfaces.ICuentaDAO;
import java.awt.Frame;
import javax.swing.JOptionPane;

/**
 * Formulario que s enecarga de generar una cuenta nueva
 *
 * @author Edgar Emir Borbon Jimenez 00000233184
 * @author Daniel Armando Peña García 000000229185
 */
public class GenerarCuentaNuevaDlg extends javax.swing.JFrame {

    Frame operacionesCliente;
    ICuentaDAO cuentaDAO;
    Cliente cliente;
    Cuenta cuenta;

    /**
     * Contructor
     *
     * @param operacionesCliente ventana por la que fue invocada
     * @param cuentaDAO control cuentaDAO
     * @param cliente cliente al que se le creara una cuenta nueva
     */
    public GenerarCuentaNuevaDlg(Frame operacionesCliente, ICuentaDAO cuentaDAO, Cliente cliente) {
        this.operacionesCliente = operacionesCliente;
        this.cuentaDAO = cuentaDAO;
        this.cliente = cliente;
        initComponents();
        this.setVisible(true);
    }

    /**
     * Se encarga de recolectar los datos del formulario y validarlos
     *
     * @return el saldo inicial de la cuenta
     */
    public Double recolecarDatos() {
        String monto = this.txtMonto.getText();
        boolean validacion = monto.matches("[0-9]{1,11}[.]?[0-9]{0,2}");
        if (validacion) {
            Double saldo = Double.parseDouble(monto);
            return saldo;
        } else {
            return null;
        }
    }

    /**
     * Crea la cuenta
     *
     * @return true si se pudo, false en caso contrario
     */
    private boolean generar() {
        Double saldo = recolecarDatos();
        if (saldo != null) {
            try {
                this.cuenta = cuentaDAO.generarCuenta(cliente, saldo);
            } catch (PersistenciaException ex) {
                JOptionPane.showMessageDialog(this, "Error no se pudo generar una cuenta", "Error", JOptionPane.ERROR_MESSAGE);
            }
            return true;
        }
        JOptionPane.showMessageDialog(this, "Ingresa un monto valido", "Error", JOptionPane.ERROR_MESSAGE);

        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCrear = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Monto Inicial de la Cuenta");

        txtMonto.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtMonto.setText("00.00");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAtras)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCrear))
                            .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(btnAtras))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     *Boton qu ejecuta la creacion de la cuenta
     * @param evt...
     */
    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
        if (generar()) {
            JOptionPane.showMessageDialog(this, "Cuenta generada con exito el numero de cuenta es: " + this.cuenta.getNumCuenta(), "Generacion de Cuenta", JOptionPane.INFORMATION_MESSAGE);
            operacionesCliente.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    /**
     * Boton que regresa a la ventana anterior
     * @param evt ...
     */
    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        operacionesCliente.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCrear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
