/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import dominio.Cuenta;
import dominio.MovimientoHistorial;
import excepciones.PersistenciaException;
import interfaces.ICuentaDAO;
import java.awt.Frame;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author trinu
 */
public class HistorialMovimientosCuenta extends javax.swing.JFrame {

    Frame operacionCliente;
    Cuenta cuenta;
    ICuentaDAO cuentaDAO;

    /**
     * Creates new form HistorialMovimientosCuenta
     */
    public HistorialMovimientosCuenta(Frame operacionCliente, Cuenta cuenta, ICuentaDAO cuentaDAO) {
        this.operacionCliente = operacionCliente;
        this.cuenta = cuenta;
        this.cuentaDAO = cuentaDAO;
        initComponents();
        cargarTablaHisotrialMovimientos();
        this.setVisible(true);
    }

    private void cargarTablaHisotrialMovimientos() {
        try {
            List<MovimientoHistorial> historial = this.cuentaDAO.hisotrialMovimientos(this.cuenta);
            DefaultTableModel modeloTabla = (DefaultTableModel) this.tblHistorial.getModel();
            modeloTabla.setRowCount(0);
            historial.forEach(movimiento -> {
                Object[] fila = {
                    movimiento.getTipo(),
                    movimiento.getNumCuenta(),
                    movimiento.getMonto(),
                    movimiento.getFecha()
                };
                modeloTabla.addRow(fila);

            });
        } catch (PersistenciaException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelHistorial = new javax.swing.JLabel();
        labelCuenta = new javax.swing.JLabel();
        lblNumCuenta = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tablaMovimientos = new javax.swing.JScrollPane();
        tblHistorial = new javax.swing.JTable();
        btnAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        labelHistorial.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelHistorial.setText("Historial Movimientos");

        labelCuenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelCuenta.setText("Cuenta:");

        lblNumCuenta.setText(cuenta.getNumCuenta());

        tblHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo Movimiento", "Numero de Cuenta", "Monto", "Fecha y Hora"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaMovimientos.setViewportView(tblHistorial);

        btnAtras.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAtras)
                        .addGap(0, 619, Short.MAX_VALUE))
                    .addComponent(tablaMovimientos))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tablaMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAtras)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelHistorial)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelCuenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNumCuenta)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelHistorial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCuenta)
                    .addComponent(lblNumCuenta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        operacionCliente.setEnabled(true);
        dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelCuenta;
    private javax.swing.JLabel labelHistorial;
    private javax.swing.JLabel lblNumCuenta;
    private javax.swing.JScrollPane tablaMovimientos;
    private javax.swing.JTable tblHistorial;
    // End of variables declaration//GEN-END:variables
}
