/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import dominio.Cliente;
import dominio.Direcciones;
import encriptador.Encriptador;
import excepciones.PersistenciaException;
import interfaces.IClienteDAO;
import interfaces.IDireccionesDAO;
import java.awt.Frame;
import java.sql.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * Formulario que registra a un nuevo cliente
 *
 * @author Edgar Emir Borbon Jimenez 00000233184
 * @author Daniel Armando Peña García 000000229185
 */
public class RegistrarClienteDlg extends javax.swing.JFrame {

    Frame menu;
    Cliente cliente = null;
    private final IDireccionesDAO direccionesDAO;
    private final IClienteDAO clientesDAO;

    /**
     * Contructor
     *
     * @param menu ventana por la que fue invocado
     * @param direccionesDAO control direccionesDAO
     * @param clienteDAO control clienteDAO
     */
    public RegistrarClienteDlg(Frame menu, IDireccionesDAO direccionesDAO, IClienteDAO clienteDAO) {
        this.menu = menu;
        this.direccionesDAO = direccionesDAO;
        this.clientesDAO = clienteDAO;
        initComponents();
        this.setVisible(true);
    }

    /**
     * Se encarga de registrar al nuevo cliente
     */
    private void registrar() {
        char[] confirmar = passConfirmarContrasena.getPassword();
        String passConfirmar = new String(confirmar);
        char[] contrasena = passContrasena.getPassword();
        String passContrasena = new String(contrasena);
        System.out.println("Confirmar: " + passConfirmar + " Contraseña: " + passContrasena);
        if (passConfirmar.equals(passContrasena)) {
            String nombre = txtNombre.getText();
            String apellidoP = txtApellidoPaterno.getText();
            String apellidoM = txtApellidoMaterno.getText();
            int diaNacimiento = Integer.parseInt(spinnerDia.getValue().toString());
            int mesNacimiento = Integer.parseInt(spinnerMes.getValue().toString());
            int anhioNacimiento = Integer.parseInt(txtAno.getText());
            Date fechaNacimiento = new Date(anhioNacimiento, mesNacimiento, diaNacimiento);
            String calle = txtCalle.getText();
            String colonia = txtColonia.getText();
            String numero = txtNumero.getText();
            String celular = txtCelular.getText();
            String contrasenaEncriptada = encriptar();

            try {
                Direcciones direccion = new Direcciones(calle, colonia, numero);
                Direcciones direcciones = direccionesDAO.insertarDireccion(direccion);
                cliente = new Cliente(nombre, apellidoP, apellidoM, fechaNacimiento, celular, contrasenaEncriptada, direcciones.getId());
                Cliente nuevoCliente = clientesDAO.registrarCliente(cliente);
            } catch (PersistenciaException ex) {
                Logger.getLogger(RegistrarClienteDlg.class.getName()).log(Level.SEVERE, null, ex);
            }
            menu.setVisible(true);
            dispose();
        } else if (txtCelular.getText().length() != 10) {
            JOptionPane.showMessageDialog(null, "El número celular debe ser\n"
                    + "de 10 carácteres", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Contraseñas no coinciden", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelNombre = new javax.swing.JLabel();
        labelApellidoPaterno = new javax.swing.JLabel();
        labelApellidoMaterno = new javax.swing.JLabel();
        labelCalle = new javax.swing.JLabel();
        labelColonia = new javax.swing.JLabel();
        labelNumero = new javax.swing.JLabel();
        labelDomicilio = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellidoPaterno = new javax.swing.JTextField();
        txtApellidoMaterno = new javax.swing.JTextField();
        txtCalle = new javax.swing.JTextField();
        txtColonia = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        btnRestaurar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        labelFechaNacimiento = new javax.swing.JLabel();
        spinnerDia = new javax.swing.JSpinner();
        labelDia = new javax.swing.JLabel();
        labelMes = new javax.swing.JLabel();
        spinnerMes = new javax.swing.JSpinner();
        txtAno = new javax.swing.JTextField();
        labelAno = new javax.swing.JLabel();
        labelDatosPersonales = new javax.swing.JLabel();
        labelCelular = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        passContrasena = new javax.swing.JPasswordField();
        passConfirmarContrasena = new javax.swing.JPasswordField();
        checkVerConstrasena = new javax.swing.JCheckBox();
        checkVerConfirmacionContrasena = new javax.swing.JCheckBox();
        labelError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar Cliente");
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        labelNombre.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre.setText("Nombre");

        labelApellidoPaterno.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelApellidoPaterno.setForeground(new java.awt.Color(255, 255, 255));
        labelApellidoPaterno.setText("Apellido Paterno");

        labelApellidoMaterno.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelApellidoMaterno.setForeground(new java.awt.Color(255, 255, 255));
        labelApellidoMaterno.setText("Apellido Materno");

        labelCalle.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelCalle.setForeground(new java.awt.Color(255, 255, 255));
        labelCalle.setText("Calle: ");

        labelColonia.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelColonia.setForeground(new java.awt.Color(255, 255, 255));
        labelColonia.setText("Colonia: ");

        labelNumero.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelNumero.setForeground(new java.awt.Color(255, 255, 255));
        labelNumero.setText("Número: ");

        labelDomicilio.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelDomicilio.setForeground(new java.awt.Color(255, 255, 255));
        labelDomicilio.setText("Domicilio");

        txtNombre.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        txtApellidoPaterno.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        txtApellidoMaterno.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        txtCalle.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtCalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCalleActionPerformed(evt);
            }
        });

        txtColonia.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        txtNumero.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });

        btnRestaurar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnRestaurar.setText("Restaurar");
        btnRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurarActionPerformed(evt);
            }
        });

        btnAceptar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        labelFechaNacimiento.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelFechaNacimiento.setForeground(new java.awt.Color(255, 255, 255));
        labelFechaNacimiento.setText("Fecha de Nacimiento");

        spinnerDia.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        spinnerDia.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        labelDia.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelDia.setForeground(new java.awt.Color(255, 255, 255));
        labelDia.setText("Día");

        labelMes.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelMes.setForeground(new java.awt.Color(255, 255, 255));
        labelMes.setText("Mes");

        spinnerMes.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        spinnerMes.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        spinnerMes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        spinnerMes.setFocusable(false);

        txtAno.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        labelAno.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelAno.setForeground(new java.awt.Color(255, 255, 255));
        labelAno.setText("Año");

        labelDatosPersonales.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelDatosPersonales.setForeground(new java.awt.Color(255, 255, 255));
        labelDatosPersonales.setText("Datos Personales");

        labelCelular.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelCelular.setForeground(new java.awt.Color(255, 255, 255));
        labelCelular.setText("Celular");

        txtCelular.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Contraseña:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Confirmar Contraseña:");

        passContrasena.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        passConfirmarContrasena.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        passConfirmarContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passConfirmarContrasenaActionPerformed(evt);
            }
        });
        passConfirmarContrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passConfirmarContrasenaKeyTyped(evt);
            }
        });

        checkVerConstrasena.setBackground(new java.awt.Color(102, 102, 102));
        checkVerConstrasena.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        checkVerConstrasena.setForeground(new java.awt.Color(255, 255, 255));
        checkVerConstrasena.setText("Visible");
        checkVerConstrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkVerConstrasenaActionPerformed(evt);
            }
        });

        checkVerConfirmacionContrasena.setBackground(new java.awt.Color(102, 102, 102));
        checkVerConfirmacionContrasena.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        checkVerConfirmacionContrasena.setForeground(new java.awt.Color(255, 255, 255));
        checkVerConfirmacionContrasena.setText("Visible");
        checkVerConfirmacionContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkVerConfirmacionContrasenaActionPerformed(evt);
            }
        });

        labelError.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelFechaNacimiento)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelDia)
                                .addGap(18, 18, 18)
                                .addComponent(spinnerDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelMes)
                                .addGap(18, 18, 18)
                                .addComponent(spinnerMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelAno)
                                .addGap(18, 18, 18)
                                .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelDatosPersonales)
                            .addComponent(labelDomicilio)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelCalle)
                                .addGap(18, 18, 18)
                                .addComponent(txtCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelColonia)
                                .addGap(18, 18, 18)
                                .addComponent(txtColonia, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelNumero)
                                .addGap(18, 18, 18)
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelNombre)
                                    .addComponent(labelCelular))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(labelApellidoMaterno)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtApellidoMaterno))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(labelApellidoPaterno)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelError, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(passContrasena)
                                    .addComponent(passConfirmarContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkVerConstrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(checkVerConfirmacionContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRestaurar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(labelDatosPersonales)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelApellidoPaterno)
                    .addComponent(txtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelApellidoMaterno)
                    .addComponent(txtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCelular)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelFechaNacimiento)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDia)
                    .addComponent(spinnerDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMes)
                    .addComponent(spinnerMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAno)
                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelDomicilio)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCalle)
                    .addComponent(txtCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelColonia)
                    .addComponent(txtColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNumero)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(passContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkVerConstrasena))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passConfirmarContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkVerConfirmacionContrasena))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelError, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnRestaurar)
                    .addComponent(btnAceptar))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCalleActionPerformed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed
    /**
     * Ejecuta el registro
     *
     * @param evt...
     */
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

        registrar();
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * Regresa a la ventana anterior
     *
     * @param evt ...
     */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * Vacia los campos
     *
     * @param evt ...
     */
    private void btnRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarActionPerformed
        this.txtAno.setText("");
        this.txtApellidoMaterno.setText("");
        this.txtApellidoPaterno.setText("");
        this.txtCalle.setText("");
        this.txtColonia.setText("");
        this.txtNombre.setText("");
        this.txtNumero.setText("");
        this.txtCelular.setText("");
    }//GEN-LAST:event_btnRestaurarActionPerformed

    /**
     * Muestra o esconde el texto de la contrasena
     *
     * @param evt ...
     */
    private void checkVerConstrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkVerConstrasenaActionPerformed
        if (checkVerConstrasena.isSelected()) {
            passContrasena.setEchoChar((char) 0);
        } else {
            passContrasena.setEchoChar('•');
        }
    }//GEN-LAST:event_checkVerConstrasenaActionPerformed
    /**
     * Muestra o esconde el texto de la contrasena de confirmacion
     *
     * @param evt ...
     */
    private void checkVerConfirmacionContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkVerConfirmacionContrasenaActionPerformed
        if (checkVerConfirmacionContrasena.isSelected()) {
            passConfirmarContrasena.setEchoChar((char) 0);
        } else {
            passConfirmarContrasena.setEchoChar('•');
        }    }//GEN-LAST:event_checkVerConfirmacionContrasenaActionPerformed

    private void passConfirmarContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passConfirmarContrasenaActionPerformed

    }//GEN-LAST:event_passConfirmarContrasenaActionPerformed

    private void passConfirmarContrasenaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passConfirmarContrasenaKeyTyped
        /*char[] confirmar = passConfirmarContrasena.getPassword();
        String passConfirmar = new String(confirmar);
        char[] contrasena = passContrasena.getPassword();
        String passContrasena = new String(contrasena);
        if(passConfirmar != passContrasena){
            labelError.setText("Contraseñas no coinciden");
        }else{
            labelError.setText("Contraseñas coinciden");
        }*/
    }//GEN-LAST:event_passConfirmarContrasenaKeyTyped

    /**
     * Encipta la contrasena
     * @return La contrasena encriptada
     */
    private String encriptar() {
        char[] arrayPass = passConfirmarContrasena.getPassword();
        Encriptador encriptador = new Encriptador();
        String passCadena = new String(arrayPass);
        return encriptador.encriptar(passCadena);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRestaurar;
    private javax.swing.JCheckBox checkVerConfirmacionContrasena;
    private javax.swing.JCheckBox checkVerConstrasena;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAno;
    private javax.swing.JLabel labelApellidoMaterno;
    private javax.swing.JLabel labelApellidoPaterno;
    private javax.swing.JLabel labelCalle;
    private javax.swing.JLabel labelCelular;
    private javax.swing.JLabel labelColonia;
    private javax.swing.JLabel labelDatosPersonales;
    private javax.swing.JLabel labelDia;
    private javax.swing.JLabel labelDomicilio;
    private javax.swing.JLabel labelError;
    private javax.swing.JLabel labelFechaNacimiento;
    private javax.swing.JLabel labelMes;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNumero;
    private javax.swing.JPasswordField passConfirmarContrasena;
    private javax.swing.JPasswordField passContrasena;
    private javax.swing.JSpinner spinnerDia;
    private javax.swing.JSpinner spinnerMes;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtColonia;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
