/**
 * transferencia.java
 * 13 feb. 2023 22:46:13
 *
 */
package presentacion;

import dominio.Cuenta;
import dominio.Transferencia;
import excepciones.PersistenciaException;
import interfaces.ICuentaDAO;
import java.awt.Frame;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * Formulario que transfiere
 *
 * @author Edgar Emir Borbon Jimenez 00000233184
 * @author Daniel Armando Peña García 000000229185
 */
public class TransferenciaDlg extends javax.swing.JFrame {

    Frame operacionCliente;
    ICuentaDAO cuentaDAO;
    Cuenta cuenta;

    /**
     * Contructor
     *
     * @param operacionCliente ventana por la que fue invocada
     * @param cuenta cuenta del cliente
     * @param cuentaDAO control cuentaDAO
     */
    public TransferenciaDlg(Frame operacionCliente, Cuenta cuenta, ICuentaDAO cuentaDAO) {
        this.operacionCliente = operacionCliente;
        this.cuentaDAO = cuentaDAO;
        this.cuenta = cuenta;
        initComponents();
        this.setVisible(true);
    }

    private void transfiere() {
        String numCuentaRecibe = txtNumeroCuenta.getText();
        double monto = Double.parseDouble(txtMonto.getText());
        Transferencia transferencia = null;
        try {
            Cuenta cuentaRecibe = cuentaDAO.consultarCuenta(numCuentaRecibe);
            transferencia = cuentaDAO.tranferencia(this.cuenta, cuentaRecibe, monto);

        } catch (PersistenciaException ex) {
            Logger.getLogger(TransferenciaDlg.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (transferencia == null) {
            JOptionPane.showMessageDialog(null, "Transferencia sin éxito", "Error", JOptionPane.ERROR_MESSAGE);
            operacionCliente.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Transferencia exitosa", "Transferencia", JOptionPane.PLAIN_MESSAGE);
            operacionCliente.setVisible(true);
            dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNumeroCuenta = new javax.swing.JLabel();
        txtNumeroCuenta = new javax.swing.JTextField();
        labelMonto = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        label$ = new javax.swing.JLabel();
        btnTransferir = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        labelNumeroCuenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelNumeroCuenta.setText("No. Cuenta");

        txtNumeroCuenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtNumeroCuenta.setText("000000000000000");

        labelMonto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelMonto.setText("Monto");

        txtMonto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtMonto.setText("00.00");

        label$.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label$.setText("$");

        btnTransferir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTransferir.setText("Transferir");
        btnTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferirActionPerformed(evt);
            }
        });

        btnAtras.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNumeroCuenta)
                    .addComponent(labelMonto))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNumeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label$)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMonto)))
                .addContainerGap(104, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTransferir)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumeroCuenta)
                    .addComponent(txtNumeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMonto)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label$))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTransferir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAtras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     *Ejectua la transferencia
     * @param evt
     */
    private void btnTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferirActionPerformed
        // TODO add your handling code here:
        transfiere();
    }//GEN-LAST:event_btnTransferirActionPerformed

    /**
     * Regresa a la ventana anterior
     * @param evt
     */
    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        operacionCliente.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnTransferir;
    private javax.swing.JLabel label$;
    private javax.swing.JLabel labelMonto;
    private javax.swing.JLabel labelNumeroCuenta;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtNumeroCuenta;
    // End of variables declaration//GEN-END:variables

}
